unlink('./figure',r=TRUE)
unlink('./_site/figure',r=TRUE)
dir.create('./figure')
dir.create('./_site/figure')
Sys.setenv(PATH = paste("/usr/local/bin", Sys.getenv("PATH"), sep=":"))
servr::jekyll('.',command='/usr/local/opt/ruby/bin/jekyll build')